In [1]:
# Based on age, experience predict income
# Age, Experience are the input variables
# Income is a Target variable

In [2]:
age = [20, 21, 23, 25, 28, 30, 35, 40]
experience = [ 0,  0,  1,  2,  3,  5, 10, 12]
income = [ 43. ,  45. ,  51.5,  58. ,  66.5,  75.5,  98. , 113. ]

In [3]:
import numpy as np
Age = np.array(age)
Exp = np.array(experience)
Inc = np.array(income)


In [4]:
# Find out the mean of every input variable
age_mean = Age.mean()
exp_mean = Exp.mean()

In [5]:
# write a correlation function
def corr(x,y):
    dx = x - x.mean()
    dy = y - y.mean()
    num = (dx*dy).sum()
    dleft = (dx**2).sum()
    dright = (dy**2).sum()
    den = (dleft * dright)**0.5
    return num/den

In [6]:
corr(Age,Exp) # perfect positive

0.985022087314044

In [7]:
corr(Exp,Inc)

0.9954551681741046

In [8]:
# Prepare input matrix to insert ones data

ones = np.ones(len(Age))

In [9]:
ones


array([1., 1., 1., 1., 1., 1., 1., 1.])

In [10]:
x = np.c_[ones,Age,Exp]

In [11]:
x

array([[ 1., 20.,  0.],
       [ 1., 21.,  0.],
       [ 1., 23.,  1.],
       [ 1., 25.,  2.],
       [ 1., 28.,  3.],
       [ 1., 30.,  5.],
       [ 1., 35., 10.],
       [ 1., 40., 12.]])

In [12]:
x.shape

(8, 3)

In [13]:
# Output matrix
y = np.c_[Inc]
y.shape

(8, 1)

In [14]:

y

array([[ 43. ],
       [ 45. ],
       [ 51.5],
       [ 58. ],
       [ 66.5],
       [ 75.5],
       [ 98. ],
       [113. ]])

In [15]:
# The formula is w = (x.t * x)**-1 . (x.t*y)
from numpy.linalg import inv
w = inv(x.T.dot(x)).dot(x.T.dot(y))
w.shape
w

array([[3. ],
       [2. ],
       [2.5]])

In [16]:
# array([[3. ], --> intercept 
#        [2. ], --> slope of age
#        [2.5]]) --. slope of Experience

In [17]:
# prediction
ycap = x.dot(w)
ycap

array([[ 43. ],
       [ 45. ],
       [ 51.5],
       [ 58. ],
       [ 66.5],
       [ 75.5],
       [ 98. ],
       [113. ]])

In [18]:
comp = np.c_[y, ycap]
comp

array([[ 43. ,  43. ],
       [ 45. ,  45. ],
       [ 51.5,  51.5],
       [ 58. ,  58. ],
       [ 66.5,  66.5],
       [ 75.5,  75.5],
       [ 98. ,  98. ],
       [113. , 113. ]])

In [19]:
# to test the quality of prediction --> Rsquare is used

rss = ((y - ycap)**2).sum()
tss = ((y - y.mean())**2).sum()
r = 1 - (rss/tss)
r

1.0

In [20]:
def rsquare(y,ycap):
    rss = ((y - ycap)**2).sum()
    tss = ((y - y.mean())**2).sum()
    r = 1 - (rss/tss)
    return r

In [21]:
accuracy = rsquare(y,ycap) * 100

In [22]:
print("accuarcy of model is ", accuracy)

accuarcy of model is  100.0


In [23]:
# Task 2: We need to predict salary. based on the age and experience.

new_age = [21, 20, 39, 40]
new_exp = [0, 0, 11, 12]


In [24]:
age = np.array(new_age)
exp = np.array(new_exp)

In [25]:
corr(age, exp) # perfect positive

0.9990162780146166

In [26]:
# prepare input matrix
ones = np.ones(len(age))
ones.shape

(4,)

In [27]:
ones

array([1., 1., 1., 1.])

In [28]:
x = np.c_[ones, age, exp]

In [29]:
x

array([[ 1., 21.,  0.],
       [ 1., 20.,  0.],
       [ 1., 39., 11.],
       [ 1., 40., 12.]])

In [31]:
salary = x.dot(w)
salary.shape

(4, 1)

In [32]:
salary


array([[ 45. ],
       [ 43. ],
       [108.5],
       [113. ]])

In [33]:
np.c_[age, exp, salary]

array([[ 21. ,   0. ,  45. ],
       [ 20. ,   0. ,  43. ],
       [ 39. ,  11. , 108.5],
       [ 40. ,  12. , 113. ]])